name CI for project

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "Hello, GitHub Actions"

    - name: Show date
      run: date